onimp/oni_multiplayer

MultiplayerMod/Multiplayer/Components/DrawCursorComponent.cs, MultiplayerMod/MultiplayerMod.csproj
Also I've added a ghost cursor if the other player cursor is out of the view.
=> Fix cursor rendering

MultiplayerMod/Game/Chores/ChoreConsumerEvents.cs, MultiplayerMod/Multiplayer/Debug/WorldDebugSnapshot.cs
- include state machine states
- add chore providers and their chores back
- reduce multipliers for hashed values since they are batched.
=> #23 Improve error counter

MultiplayerMod/Core/Unity/UnityObject.cs
Please read the comment in code. I think this should properly fix the issue with GC.
=> Fix cached pointer usage

MultiplayerMod/Game/Screens/UserMenuButtonEvents.cs, MultiplayerMod/Multiplayer/Commands/Screens/UserMenu/ClickUserMenuButton.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs
All buttons should be synced except: CopySettings, MoveToLocation, Show navigation, Follow cam
=> #21 Sync user menu side buttons.

README.md, docs/CONTRIBUTING.md
Adds a guide inside of the readme.md to start working on the mod for contributers.
Not a native speaker, so might need some edits to words or sentences 😄
=> Add how to develop

MultiplayerMod/Multiplayer/Commands/Screens/Consumable/PermitConsumableToMinion.cs, MultiplayerMod/Multiplayer/Commands/Screens/Priorities/SetPersonalPriority.cs, MultiplayerMod/Multiplayer/Commands/Screens/Skill/MasterSkill.cs, MultiplayerMod/Multiplayer/Commands/Screens/Skill/SetHat.cs
In case of existing desyncs (dupes list) syncing some commands would cause NPE.
=> #98 Add safety null checks.

MultiplayerMod/Multiplayer/World/Debug/WorldDebugSnapshotRunner.cs
Surrounded entire interaction into try catch.
=> #119 Fix world debugger NPE.

MultiplayerMod/Multiplayer/Commands/Screens/Schedule/ChangeSchedulesList.cs, MultiplayerMod/Multiplayer/Commands/Screens/UserMenu/ClickUserMenuButton.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerObjects.cs
This is more reliable way to identify objects and sync those created after hard sync.
=> #118 Replace KPrefabeId usage with MultiplayerId.

MultiplayerMod/Game/Mechanics/FilterEvents.cs, MultiplayerMod/Multiplayer/Commands/Screens/Filters/AddTagToFilter.cs, MultiplayerMod/Multiplayer/Commands/Screens/Filters/RemoveTagFromFilter.cs, MultiplayerMod/Multiplayer/Commands/Screens/Filters/SetFilter.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs
Examples:
FoodBox - TreeFilterableSideScreen
LiquidFilter - FilterSideScreen
=> #92 Sync filterable side screens.

MultiplayerMod/Game/Mechanics/Objects/ObjectEvents.cs, MultiplayerMod/Game/Mechanics/Objects/ObjectEventsArgs.cs, MultiplayerMod/Game/Mechanics/Objects/TargetExtractor.cs, MultiplayerMod/Multiplayer/Commands/Gameplay/CallMethod.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerObjects.cs
PassengerRocketModule, RocketControlStation, ICheckboxControl, SuitLocker, IThresholdSwitch, ISliderControl, Valve.
Added support for interface as patch target type.
=> #92 Sync more side screen objects.

MultiplayerMod/Core/Extensions/EnumerableExtensions.cs, MultiplayerMod/Core/Loader/ModLoader.cs, MultiplayerMod/Core/Patch/HarmonyOptionalAttribute.cs, MultiplayerMod/Game/Dev/DevToolSceneInspectorPatch.cs
- Adds support for optional patching using `[HarmonyOptional]`.
=> Optional patches

MultiplayerMod/Core/Loader/ModLoader.cs, MultiplayerMod/Directory.Build.targets, MultiplayerMod/MultiplayerMod.csproj, MultiplayerMod/mod_info.yaml
New features:
- Assembly version is resolved from git
- Mod info (mod_info.yaml) is auto-generated
- Version contains commit hash.
=> Add automated build version generation

MultiplayerMod/Game/Mechanics/Printing/TelepadEvents.cs, MultiplayerMod/Multiplayer/Commands/Gameplay/AcceptDelivery.cs, MultiplayerMod/Multiplayer/Commands/Gameplay/RejectDelivery.cs, MultiplayerMod/Multiplayer/Commands/Screens/Schedule/ChangeSchedulesList.cs
The reason was in missed clear call of synced bioprinter deliverables list.
=> #179 Fix not random bioprinter.

MultiplayerMod/Core/Loader/DelayedModLoader.cs, MultiplayerMod/Core/Loader/LaunchInitializerPatch.cs, MultiplayerMod/Core/Loader/ModLoader.cs
Features:
- The mod now starts to load when all resources that can be used in static fields are loaded (theoretically).
- As a side feature we now have mod list available.
=> #183 Add delayed mod loader

MultiplayerMod/Game/Mechanics/Printing/TelepadEvents.cs, MultiplayerMod/Multiplayer/Commands/Gameplay/AcceptDelivery.cs
ProxyId exists and should be synced for minions only (MinionIdentity component is present).
=> #182 Fix NPE if printing non duplicant (crate package).

MultiplayerMod/Game/Mechanics/Objects/ComponentEventsArgs.cs, MultiplayerMod/Game/Mechanics/Objects/ObjectEvents.cs, MultiplayerMod/Game/Mechanics/Objects/StateMachineEventsArgs.cs, MultiplayerMod/Game/Mechanics/Objects/TargetExtractor.cs, MultiplayerMod/Multiplayer/Commands/Gameplay/CallMethod.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs, MultiplayerMod/Multiplayer/Objects/Reference/ComponentReference.cs, MultiplayerMod/Multiplayer/Objects/Reference/GameObjectReference.cs, MultiplayerMod/Multiplayer/Objects/Reference/StateMachineReference.cs, MultiplayerMod/Multiplayer/Objects/StateMachineReferenceExtensions.cs
NPE was caused by some events coming from non KMonoBehaviour - StateMachine.Instance.
Add reference mechanism for the type as well.
=> #191 Fix NPE in creature building.

MultiplayerMod/Core/Patch/PatchTargetResolver.cs, MultiplayerMod/Game/Mechanics/Objects/ObjectEvents.cs, MultiplayerMod/Platform/Steam/Network/Messaging/Surrogates/RoomSurrogate.cs, MultiplayerMod/Platform/Steam/Network/Messaging/Surrogates/SerializationSurrogates.cs
Also added validation for all other arguments for their serialization.
=> #207 Fix `Room is not serializable`.

MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs
This is a temporary fix, as it's a critical issue. 
The whole approach will be revisited in later releases.
=> #216 Fix objects events handling

src/MultiplayerMod/Game/UI/Tools/Events/InterfaceToolEvents.cs, src/MultiplayerMod/Multiplayer/Commands/Player/UpdatePlayerCursorPosition.cs, src/MultiplayerMod/Multiplayer/Components/CursorComponent.cs, src/MultiplayerMod/Multiplayer/Components/CursorManager.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/GameEventsBinder.cs, src/MultiplayerMod/Multiplayer/Players/Events/PlayerCursorPositionUpdatedEvent.cs
Cursor become semi-transparent. Text about current screen is shown only if players are on different screens.
=> #79 Change cursor color and text if players on different screens.

src/MultiplayerMod/Multiplayer/Components/CursorComponent.cs
Perhaps we can provide a setting to enable it back later on.
=> #79 Disable relative cursor by default.

src/MultiplayerMod/ModRuntime/Loader/DelayedModLoader.cs, src/MultiplayerMod/ModRuntime/RuntimeReadyEvent.cs, src/MultiplayerMod/Multiplayer/Objects/MultiplayerId.cs, src/MultiplayerMod/Multiplayer/Objects/MultiplayerObjects.cs, src/MultiplayerMod/Multiplayer/UI/Dev/DevToolMultiplayerObjects.cs, src/MultiplayerMod/Multiplayer/UI/Dev/DevToolsConfigurer.cs
This will be used as a base for the multiplayer chores dev tool.
=> #298 Add multiplayer objects dev tool

src/MultiplayerMod.Test/Environment/Unity/UnityTestRuntime.cs, src/MultiplayerMod.Test/Game/Chores/ChoreEventsTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/CreateHostChoreTest.cs, src/MultiplayerMod.Test/MultiplayerMod.Test.csproj, src/MultiplayerMod/Game/Chores/ChoreEvents.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/CreateHostChore.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs, src/MultiplayerMod/Multiplayer/Patches/DisableClientChorePatch.cs, src/MultiplayerMod/Platform/Steam/Network/Messaging/Surrogates/ScheduleBlockTypeSurrogate.cs, src/MultiplayerMod/Platform/Steam/Network/Messaging/Surrogates/SerializationSurrogates.cs
Add patch to disable chores creation on client.
=> #11 Add event to send Host chore creation to clients.

src/MultiplayerMod.Test/Game/Chores/AbstractChoreTest.cs, src/MultiplayerMod.Test/Game/Chores/States/ChoreStateEventsTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/TransitChoreToStateTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/DisableChoreStateTransitionTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/DisableUpdateCallbackTest.cs, src/MultiplayerMod.Test/Multiplayer/States/StatesManagerTest.cs, src/MultiplayerMod.Test/Multiplayer/States/WaitHostStateTest.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/DisableUpdateCallback.cs, src/MultiplayerMod/Multiplayer/States/StatesManager.cs
Add tests assertions to make sure that entire ChoreList config is tested. 
Fix type issues in patch (harmony could inject any type in any argument regardless its type).
=> #13 Disable update calls on client.

src/MultiplayerMod.Test/Game/Chores/AbstractChoreTest.cs, src/MultiplayerMod.Test/Game/Chores/States/ChoreStateEventsTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/SetStateArgumentsTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/DisableChoreStateTransitionTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/DisableEventCallbackTest.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/SetStateArguments.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/DisableEventCallback.cs
Added SetStateArguments.cs command used by both transitions. Disable event handlers for Event transitions.
=> #13 Fully implement state syncs for Update and EventHandler transitions.

src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/AdjustStateMachineTransitionsTest.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/AdjustStateMachineTransitions.cs
Removes EventTransition handlers.
Removes Enter handlers.
Removes update handlers.
=> #13 Adjust state machines for moveTo syncs.

src/MultiplayerMod.Test/Game/Chores/AbstractChoreTest.cs, src/MultiplayerMod.Test/Game/Chores/States/ChoreStateEventsTest.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Game/Chores/States/MoveToArgs.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs
Move start and move update is quite different in comparision to regular state enter / update, because they does not change state machine they do manipulate with Navigator instead.
=> #13 Implement move sync related events.

src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/StartMoveTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/UpdateMoveTest.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Game/Chores/States/MoveToArgs.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/StartMove.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/UpdateMove.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs
Also connect all move related events to corresponding commands.
=> #13 Implement StartMove and UpdateMove commands.

src/MultiplayerMod.Test/Core/Collections/BidirectionalMapTests.cs, src/MultiplayerMod.Test/Core/Collections/ObjectExtensionMapTests.cs, src/MultiplayerMod/Core/Collections/BidirectionalMap.cs, src/MultiplayerMod/Core/Collections/IdentityEqualityComparer.cs, src/MultiplayerMod/Core/Collections/ObjectExtensionMap.cs
Object extension map implementation that will be required for generalized multiplayer objects repository.
=> Multiplayer objects repository: object extension map

src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Game/NameOf/StateMachineMemberReference.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/SetStateArguments.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/StartMove.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/UpdateMove.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/AdjustStateMachineTransitions.cs, src/MultiplayerMod/Multiplayer/States/ContinuationState.cs, src/MultiplayerMod/Multiplayer/States/IWaitHostState.cs, src/MultiplayerMod/Multiplayer/States/StatesManager.cs, src/MultiplayerMod/Multiplayer/States/WaitHostState.cs
=> Replace string references with nameof

src/MultiplayerMod/Multiplayer/Commands/ArgumentUtils.cs, src/MultiplayerMod/Multiplayer/Objects/MultiplayerObjects.cs
The issue was caused by 0 amount and underlying assert in the constructor of FetchOrder.
=> #340 Fix fetchRef failure.
