onimp/oni_multiplayer

MultiplayerMod/Core/Loader/ModLoader.cs, MultiplayerMod/Core/Logging/LogLevel.cs, MultiplayerMod/Core/Logging/Logger.cs, MultiplayerMod/Core/Logging/LoggerFactory.cs, MultiplayerMod/Core/Scheduling/UnityTaskSchedulerLoader.cs, MultiplayerMod/Multiplayer/Commands/Chores/FindNextChore.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs, MultiplayerMod/Multiplayer/Configuration/MultiplayerCoordinator.cs, MultiplayerMod/Multiplayer/Configuration/ServerEventBindings.cs, MultiplayerMod/Multiplayer/Debug/WorldDebugSnapshot.cs, MultiplayerMod/Multiplayer/State/MultiplayerState.cs, MultiplayerMod/Platform/Steam/Network/Components/LobbyJoinRequestComponent.cs, MultiplayerMod/Platform/Steam/Network/Messaging/NetworkMessageProcessor.cs, MultiplayerMod/Platform/Steam/Network/SteamClient.cs, MultiplayerMod/Platform/Steam/Network/SteamLobby.cs, MultiplayerMod/Platform/Steam/Network/SteamServer.cs, MultiplayerMod/Platform/Steam/SteamPlatformLoader.cs
To change the global log level use log.level=<level> as a command line argument. 
To change the specific logger log level use log.<logger name>=<level>. 
The levels are: trace, debug, info, warning, error.
=> Add customizable log levels

MultiplayerMod/Game/Chores/ChoreConsumerEvents.cs, MultiplayerMod/Multiplayer/Commands/Chores/FindNextChore.cs
Search criteria was too strict and was always checking for chore position which wont match in case of dupe position desync.
TODO:
- FetchChore still missing on client side.
- If host re-assign chore client does not comply with it (even that receiving and executing chores) (race condition?).
- Retry might become redundant now.
- If host completes a chore earlier - it will send IdleChore to the client with an unfinished chore.
I'll either adress those TODO before clossing a ticket (more PR will be created) or create separate tickets.
=> #11 Fix missing IdleChore and MoveToSafetyChore.

MultiplayerMod/Game/Chores/HostChores.cs, MultiplayerMod/Multiplayer/Commands/Chores/FindNextChore.cs, MultiplayerMod/Multiplayer/Patches/ChoreConsumerPatch.cs
Replaced Dictionary type of chores to have a queue instead of single value. However I didn't see occasions of having more than 1 element in the queue.
TODO:
- FetchChore still missing on client side.
- If host re-assign chore client does not comply with it (even that receiving and executing chores).
- New observation: dupe that must cancel chore - does not do chore, however run to the job site. Another dupe who must do chore does not move, but does chore upon first dupe arrival (from a distance).
- If host completes a chore earlier... - created ticket #56
=> #11 Remove retries since they do not fix any issues for now.

MultiplayerMod/Core/Unity/GameObjectExtension.cs, MultiplayerMod/Multiplayer/Commands/ShowOverlay.cs, MultiplayerMod/Multiplayer/Configuration/MultiplayerCoordinator.cs, MultiplayerMod/Multiplayer/World/WorldManager.cs, MultiplayerMod/mod_info.yaml
#51 Fix client failures during host save/sync. Show overlay while syn…c on clients only.
The issue was caused by handling cursor position messages while sync (world is loading). As a fix - reset worldSpawned state + make sure that DrawCursorComponent.cs does not exist while game is loading by making it limited to a single scene only (undo DoNotDestroyOnLoad).
=> #51 Fix client failures during host save/sync

MultiplayerMod/Game/World/PauseScreenEvents.cs, MultiplayerMod/Multiplayer/Configuration/MultiplayerCoordinator.cs, MultiplayerMod/Platform/Steam/Network/SteamClient.cs, MultiplayerMod/Platform/Steam/Network/SteamServer.cs
Now client/host can disconnect from the game and start new one without restarting the game.
=> #26 Fix disconnects from MP game.

MultiplayerMod/Multiplayer/World/WorldManager.cs, MultiplayerMod/mod_info.yaml
Problem was with using AutoSave filename for saving instead of active file name. This was causing during default autosave logic since it is relying on the filename to contain special text pattern (`Cycle XX`), while autosave file does not have it. Fixed by asung current filename (which is in the right format).
Be aware that old save files seems to be affected, hence it is required to start a new game to have fix applied.
=> #68 Fix autosave not enough space issue.

MultiplayerMod/Core/Unity/UnityObject.cs, MultiplayerMod/mod_info.yaml
Error was caused by fake Unity objects created with m_CachedPtr == 1. Replace with allocated memory instead.
=> Fix error during hard sync.

MultiplayerMod/Game/Mechanics/AccessControlEventArgs.cs, MultiplayerMod/Game/Mechanics/AccessControlEvents.cs, MultiplayerMod/Multiplayer/Commands/Mechanics/Access/AbstractAccessControlCommand.cs, MultiplayerMod/Multiplayer/Commands/Mechanics/Access/ChangeDefaultPermission.cs, MultiplayerMod/Multiplayer/Commands/Mechanics/Access/ChangePermission.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs, MultiplayerMod/Multiplayer/Objects/GameObjectExtensions.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerId.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerReference.cs
This provides access synchronization for anything that has `AccessControl`, e.g. doors.
**Bonus**: "Copy Settings" tool works fine with these changes, even the access screen is refreshed.
=> #123 Add access control sync

MultiplayerMod/Game/MainMenuExtensions.cs, MultiplayerMod/Game/UI/Screens/Events/SideScreenEvents.cs, MultiplayerMod/Multiplayer/Commands/Screens/UserMenu/ClickUserMenuButton.cs, MultiplayerMod/Multiplayer/Commands/Screens/UserMenu/InteractWithSideScreen.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs
Currently it filters out all side screen since they were not tested. Idea is to go through each of them and make sure that the event and command covers all required action syncs. It is possible that some sidescreens couldn't be easily synced through general event. However the idea is to cover 80%+ of sidescreens with general to avoid creating 70+ different events and commands.
=> #92 Add general event and command for side screens.

MultiplayerMod/Multiplayer/Configuration/CommandExceptionHandler.cs, MultiplayerMod/Multiplayer/Configuration/MultiplayerCoordinator.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerObjectNotFoundException.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerObjects.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerReference.cs
Now we can safely use `MultiplayerReference.GetGameObject` or `MultiplayerReference.GetComponent<T>`.
=> #146 Add command exception handler

MultiplayerMod/Multiplayer/Commands/Screens/Schedule/ChangeSchedulesList.cs, MultiplayerMod/Multiplayer/Commands/Screens/UserMenu/ClickUserMenuButton.cs, MultiplayerMod/Multiplayer/Objects/MultiplayerReference.cs
Previous checks were vague and allowing further command execution in case of not found object. Switch to MultiplayerReference to get an exception (handled) in case of not synced objects.
=> #145 Fix NPE in ChangeSchedulesList.cs and ClickUserMenuButton.cs for newly created objects.

MultiplayerMod/Game/Mechanics/Objects/ObjectEvents.cs
This was causing host crash after few minutes of MP game as well.
=> Fix a lot of warnings due to generic method being patched.

MultiplayerMod/Core/Patch/Context/PatchContext.cs, MultiplayerMod/Core/Patch/Context/PatchContextFailedIntegrityException.cs, MultiplayerMod/Core/Patch/Context/PatchContextGuard.cs, MultiplayerMod/Core/Patch/PatchControl.cs, MultiplayerMod/Game/Mechanics/Minions/MinionDeliveryState.cs, MultiplayerMod/Game/UI/Screens/Events/PrioritiesScreenEvents.cs, MultiplayerMod/Game/World/WorldGenSpawnerEvents.cs, MultiplayerMod/Multiplayer/Configuration/GameEventBindings.cs, MultiplayerMod/Multiplayer/Configuration/MultiplayerCoordinator.cs
Seems there are cases when we have to enable or disable patches hierarchically, so we have to have a stackable context for easier use.
New features:
- Stackable context.
- Global context (Enable / disable patches globally).
- Patch context stack guard (Helps to spot problems with manual `Enter` `Leave` invocations).
=> Stackable patch context

src/MultiplayerMod.Test/Core/Dependency/DependencyContainerBuilderTests.cs, src/MultiplayerMod.Test/Multiplayer/MultiplayerTools.cs, src/MultiplayerMod/Core/Dependency/DependencyContainerBuilder.cs, src/MultiplayerMod/Core/Scheduling/UnityTaskSchedulerConfigurer.cs, src/MultiplayerMod/Multiplayer/Commands/MultiplayerCommandAttribute.cs, src/MultiplayerMod/Multiplayer/Commands/MultiplayerCommandContext.cs, src/MultiplayerMod/Multiplayer/Commands/MultiplayerCommandRuntimeAccessor.cs, src/MultiplayerMod/Multiplayer/Commands/MultiplayerCommandsConfigurer.cs, src/MultiplayerMod/Multiplayer/Commands/Registry/MultiplayerCommandAlreadyRegisteredException.cs, src/MultiplayerMod/Multiplayer/Commands/Registry/MultiplayerCommandConfiguration.cs, src/MultiplayerMod/Multiplayer/Commands/Registry/MultiplayerCommandInvalidInterfaceException.cs, src/MultiplayerMod/Multiplayer/Commands/Registry/MultiplayerCommandNotFoundException.cs, src/MultiplayerMod/Multiplayer/Commands/Registry/MultiplayerCommandRegistry.cs, src/MultiplayerMod/Multiplayer/Commands/Tools/AbstractBuildUtilityCommand.cs, src/MultiplayerMod/Multiplayer/Commands/Tools/AbstractDragToolCommand.cs, src/MultiplayerMod/Multiplayer/CoreOperations/CommandExecution/MultiplayerCommandExecutor.cs, src/MultiplayerMod/Multiplayer/CoreOperations/PlayersManagement/Commands/InitializeClientCommand.cs, src/MultiplayerMod/Multiplayer/CoreOperations/PlayersManagement/Commands/RequestPlayerStateChangeCommand.cs, src/MultiplayerMod/Multiplayer/CoreOperations/PlayersManagement/PlayersManagementController.cs, src/MultiplayerMod/Network/MultiplayerCommandOptions.cs, src/MultiplayerMod/Platform/Steam/Network/SteamServer.cs, src/MultiplayerMod/Platform/Steam/SteamPlatformConfigurer.cs
The original approach was overflexible and allowed for the same command to be executed either on a server or a client. But now I see this as an exception from a general principle: one command - one target. 
Now the target is configurable via the `MultiplayerCommand` attribute and it's less error-prone.
(Also it uncovers an issue with platform implementation segregation, we should revise it next QoL iteration)
=> Command registry

src/MultiplayerMod.Test/Multiplayer/MultiplayerConnectionTests.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Events/ConnectionLostEvent.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Events/GameQuitEvent.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Events/StopMultiplayerEvent.cs, src/MultiplayerMod/Multiplayer/CoreOperations/ExecutionLevelController.cs, src/MultiplayerMod/Multiplayer/CoreOperations/GameStateEventsRelay.cs, src/MultiplayerMod/Multiplayer/CoreOperations/MultiplayerServerController.cs, src/MultiplayerMod/Multiplayer/CoreOperations/PlayersManagement/PlayersManagementController.cs, src/MultiplayerMod/Multiplayer/UI/Notifications.cs, src/MultiplayerMod/Platform/Steam/Network/SteamClient.cs
Current implementation does not distinguish between server leave and crash.
=> #66 Kick client if server leaves/crashes.

src/MultiplayerMod.AttributeProcessor.MSBuild.Task/ProcessAttributes.cs
For some reason, on my machine, building the solution failed while running the `AttributeProcessor` MSBuild task. The issue being that msbuild.exe held a reference to the `MultiplayerMod.Original.dll` file after opening with `ModuleDefMD.Load()`. It would then fail to delete the file during cleanup. I've simply changed it to open a stream and close it after reading the file. I figured I couldn't be the only one this is affecting. Though in all probability it's something to do with my build environment. Figured I'd throw this up here in case you're interested.
VS2022
x64
Windows 10
Love the mod!
=> Fixed msbuild holding dll lock during AttributeProcessor task

src/MultiplayerMod/Multiplayer/Components/AssignedMultiplayerPlayer.cs, src/MultiplayerMod/Multiplayer/Components/CursorComponent.cs, src/MultiplayerMod/Multiplayer/Components/CursorManager.cs, src/MultiplayerMod/Multiplayer/Components/DestroyOnPlayerLeave.cs
Initial game object initialization was moved into `CursorManager`.
New components:
- `AssignedMultiplayerPlayer` - binds a game object to a multiplayer player
- `DestroyOnPlayerLeave` - can be used on game objects that should be destroyed if a player leaves
Now a single player cursor has the following game object structure:
- Cursor main game object [CursorComponent, Canvas, AssignedMultiplayerPlayer, DestroyOnPlayerLeave]
- Cursor group game object
- Pointer image [Image]
- Player name and screen [TextMeshProUGUI]
=> #243 Fix player cursor

src/MultiplayerMod.Test/AbstractGameTest.cs, src/MultiplayerMod.Test/Game/Chores/ChoreEventsTest.cs, src/MultiplayerMod.Test/Game/Chores/ChoreListTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/CreateHostChoreTest.cs, src/MultiplayerMod.Test/MultiplayerMod.Test.csproj, src/MultiplayerMod/Game/Chores/ChoreEvents.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Game/Mechanics/Objects/ObjectEvents.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/CreateHostChore.cs, src/MultiplayerMod/Multiplayer/Commands/Screens/Consumable/PermitConsumableToMinion.cs, src/MultiplayerMod/Multiplayer/Commands/Screens/Priorities/SetPersonalPriority.cs, src/MultiplayerMod/Multiplayer/Commands/Screens/Skill/MasterSkill.cs, src/MultiplayerMod/Multiplayer/Commands/Screens/Skill/SetHat.cs, src/MultiplayerMod/Multiplayer/Objects/ComponentReferenceExtensions.cs, src/MultiplayerMod/Multiplayer/Objects/GameObjectExtensions.cs, src/MultiplayerMod/Multiplayer/Objects/Reference/ComponentReference.cs, src/MultiplayerMod/Multiplayer/Patches/DisableClientChorePatch.cs, src/MultiplayerMod/Platform/Steam/Network/Messaging/Surrogates/EmoteSurrogate.cs
Also disabled chores with Func arguments since some of them can not be serialised (MoveChore has lambda and Delegate's Target is not replaced with a reference)
=> #11 Add all chore types to ChoreList. Fix AttackChore causing game failure (wrong GameObject references)

src/MultiplayerMod.Test/Game/Chores/States/ChoreStateEventsTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/TransitChoreToStateTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/DisableChoreStateTransitionTest.cs, src/MultiplayerMod.Test/Multiplayer/States/StatesManagerTest.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/TransitChoreToState.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/DisableChoreStateTransition.cs, src/MultiplayerMod/Multiplayer/States/ContinuationState.cs, src/MultiplayerMod/Multiplayer/States/StatesManager.cs, src/MultiplayerMod/Multiplayer/States/WaitHostState.cs
In order to avoid cycle loops (enter -> wait -> command -> enter -> wait -> ....) introduced new state `ContinuationState` which is a copy of original enter state. Now the flow looks like: enter -> wait -> command -> continuation
=> #13 Send and execute command upon state enter transition.

src/MultiplayerMod.Test/Game/Chores/AbstractChoreTest.cs, src/MultiplayerMod/Game/Chores/ChoreList.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Game/Chores/Types/StateTransitionConfig.cs, src/MultiplayerMod/Game/Chores/Types/TransitionTypeEnum.cs
Syncing sensors themself won't guarantee state machine consistencies. So sync transitions results from cell sensor (Exit, Move).
Introduced new `transition` transition type. Basically it is similar to OnExit but will prevent undesired chore transition upon default conditions.
=> #13 Specify Chore configs for chores using sensors.

src/MultiplayerMod.Test/Game/Chores/States/ChoreStateEventsTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/AllowStateTransitionTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/TransitToStateTest.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/AllowStateTransition.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/TransitToState.cs, src/MultiplayerMod/Multiplayer/CoreOperations/Binders/HostEventsBinder.cs
Old TransitChoreToState was based on assumption that stateMachine has WaitHostState, however it is not the case for move syncs and transition syncs. For those there is no waitHostState and therefore no waiting.
=> #13 Split TransitChoreToState event to 2: AllowStateTransition and TransitToState.cs

src/MultiplayerMod.Test/Directory.Build.targets, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/StartMoveTest.cs, src/MultiplayerMod.Test/Multiplayer/Commands/Chores/States/UpdateMoveTest.cs, src/MultiplayerMod.Test/Multiplayer/Patches/Chores/States/AdjustStateMachineTransitionsTest.cs, src/MultiplayerMod.Test/MultiplayerMod.Test.csproj, src/MultiplayerMod/Core/Reflection/ReflectionExtension.cs, src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/StartMove.cs, src/MultiplayerMod/Multiplayer/Commands/Chores/States/UpdateMove.cs, src/MultiplayerMod/Multiplayer/Objects/StateMachineReferenceExtensions.cs, src/MultiplayerMod/Multiplayer/States/StatesManager.cs
Problem was undiscovered due to faulty tests which we successfully passing. Which has been resulted due to using exposed libraries while in game runtime libraries are not exposed.
Fixed by copying original libraries to test output directory. As result 69 tests has failed.
Applied fixes for those tests.
=> #13 Fix npe during state syncs.

src/MultiplayerMod/Game/Chores/States/ChoreStateEvents.cs, src/MultiplayerMod/Multiplayer/Patches/Chores/States/AdjustStateMachineTransitions.cs
Otherwise a lot of patches were skipped (the one that was happening during world load). However as an outcome - new problem being surfaced: Existing chores does not have MultiplayerId after world load.
=> #1 Enable state patches for other execution levels.

src/MultiplayerMod.Test/Multiplayer/Patches/Chores/DisableClientChoreCreationPatchTest.cs, src/MultiplayerMod/Core/Scheduling/UntiyTaskScheduler.cs
I've noticed we have several issues with the Unity task scheduler:
- Duplicated tasks (double execution was prevented by the Task implementation anyway, but still)
- Exceptions aren't forwarded to the calling method (can produce false positive outcomes)
These issues are addressed in this PR.
@zuev93 Please check ``ClientChoresMustBeCancelled(WorkChore`1[MedicinalPillWorkable],System.Func`1[System.Object[]])``
=> Fix Unity scheduler
